/* File generated by: simse.codegenerator.guigenerator.AtAGlanceTableModelGenerator */
package simse.gui;

import javax.swing.table.*;
import java.util.*;
import java.lang.*;
import java.text.*;

import simse.adts.objects.*;
import simse.state.*;


public class CodeTableModel extends AbstractTableModel
{
private Vector<String> columnNames; // column names
private Vector<Vector<Object>> data; // data in table
private State state;

private NumberFormat numFormat;

public CodeTableModel(State s)
{
state = s;
columnNames = new Vector<String>();
data = new Vector<Vector<Object>>();
numFormat = NumberFormat.getNumberInstance(Locale.US);
initColNames();
update();
}

public int getColumnCount()
{
return columnNames.size();
}

public int getRowCount()
{
if (data.size() > 0) {
return data.elementAt(0).size();
}return 0;
}

public String getColumnName(int col)
{
return columnNames.elementAt(col);
}

public int getColumnIndex(String columnName)
{
for(int i=0; i<columnNames.size(); i++)
{
String colName = columnNames.elementAt(i);
if(colName.equals(columnName))
{
return i;
}
}
return -1;
}

public Object getValueAt(int row, int col)
{
return data.elementAt(col).elementAt(row);
}

public void setValueAt(Object value, int row, int col)
{
data.elementAt(col).add(value);
fireTableCellUpdated(row, col);
}

private void initColNames()
{
columnNames.add("Description");
columnNames.add("PercentErroneous");
columnNames.add("Completeness");
columnNames.add("PercentRefactored");
columnNames.add("PercentIntegrated");
}

public void update()
{

if (!state.getClock().isStopped()) {
Vector<Code> codes = state.getArtifactStateRepository().getCodeStateRepository().getAll();
Vector<Object> temp = new Vector<Object>();
// Initialize Description:
temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
temp.add(codes.elementAt(i).getDescription());
}
if(data.size() < 1)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 0);
}

// Initialize PercentErroneous:
temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getPercentErroneous()));

}
if(data.size() < 2)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 1);
}

// Initialize Completeness:
temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getCompleteness()));

}
if(data.size() < 3)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 2);
}

// Initialize PercentRefactored:
temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getPercentRefactored()));

}
if(data.size() < 4)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 3);
}

// Initialize PercentIntegrated:
temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getPercentIntegrated()));

}
if(data.size() < 5)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 4);
}

}
else // game over
{
data.clear();
columnNames.clear();
Vector<Code> codes = state.getArtifactStateRepository().getCodeStateRepository().getAll();
Vector<Object> temp = new Vector<Object>();
// Initialize Description:
if(columnNames.contains("Description") == false)
{
columnNames.add("Description");
}temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
temp.add(codes.elementAt(i).getDescription());}
if(data.size() < 1)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 0);
}

// Initialize PercentErroneous:
if(columnNames.contains("PercentErroneous") == false)
{
columnNames.add("PercentErroneous");
}temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getPercentErroneous()));
}
if(data.size() < 2)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 1);
}

// Initialize Completeness:
if(columnNames.contains("Completeness") == false)
{
columnNames.add("Completeness");
}temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getCompleteness()));
}
if(data.size() < 3)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 2);
}

// Initialize PercentRefactored:
if(columnNames.contains("PercentRefactored") == false)
{
columnNames.add("PercentRefactored");
}temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getPercentRefactored()));
}
if(data.size() < 4)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 3);
}

// Initialize PercentIntegrated:
if(columnNames.contains("PercentIntegrated") == false)
{
columnNames.add("PercentIntegrated");
}temp = new Vector<Object>();
for(int i=0; i<codes.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(codes.elementAt(i).getPercentIntegrated()));
}
if(data.size() < 5)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 4);
}

fireTableStructureChanged();
}

fireTableDataChanged(); // notify listeners that table data has changed
}


public Class getColumnClass(int c)
{
return getValueAt(0, c).getClass();
}
}