/* File generated by: simse.codegenerator.guigenerator.AtAGlanceTableModelGenerator */
package simse.gui;

import javax.swing.table.*;
import java.util.*;
import java.lang.*;
import java.text.*;

import simse.adts.objects.*;
import simse.state.*;


public class UserStoriesTableModel extends AbstractTableModel
{
private Vector<String> columnNames; // column names
private Vector<Vector<Object>> data; // data in table
private State state;

private NumberFormat numFormat;

public UserStoriesTableModel(State s)
{
state = s;
columnNames = new Vector<String>();
data = new Vector<Vector<Object>>();
numFormat = NumberFormat.getNumberInstance(Locale.US);
initColNames();
update();
}

public int getColumnCount()
{
return columnNames.size();
}

public int getRowCount()
{
if (data.size() > 0) {
return data.elementAt(0).size();
}return 0;
}

public String getColumnName(int col)
{
return columnNames.elementAt(col);
}

public int getColumnIndex(String columnName)
{
for(int i=0; i<columnNames.size(); i++)
{
String colName = columnNames.elementAt(i);
if(colName.equals(columnName))
{
return i;
}
}
return -1;
}

public Object getValueAt(int row, int col)
{
return data.elementAt(col).elementAt(row);
}

public void setValueAt(Object value, int row, int col)
{
data.elementAt(col).add(value);
fireTableCellUpdated(row, col);
}

private void initColNames()
{
columnNames.add("Name");
columnNames.add("NumUserStoriesSpecified");
columnNames.add("Prioritized");
columnNames.add("NumUserStoriesImplemented");
columnNames.add("SpecificationCompleteness");
columnNames.add("ImplementationCompleteness");
columnNames.add("NumUserStoriesIntegrated");
columnNames.add("PercentErroneous");
}

public void update()
{

if (!state.getClock().isStopped()) {
Vector<UserStories> userstoriess = state.getArtifactStateRepository().getUserStoriesStateRepository().getAll();
Vector<Object> temp = new Vector<Object>();
// Initialize Name:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
temp.add(userstoriess.elementAt(i).getName());
}
if(data.size() < 1)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 0);
}

// Initialize NumUserStoriesSpecified:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getNumUserStoriesSpecified()));

}
if(data.size() < 2)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 1);
}

// Initialize Prioritized:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
temp.add(userstoriess.elementAt(i).getPrioritized());
}
if(data.size() < 3)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 2);
}

// Initialize NumUserStoriesImplemented:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getNumUserStoriesImplemented()));

}
if(data.size() < 4)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 3);
}

// Initialize SpecificationCompleteness:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getSpecificationCompleteness()));

}
if(data.size() < 5)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 4);
}

// Initialize ImplementationCompleteness:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getImplementationCompleteness()));

}
if(data.size() < 6)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 5);
}

// Initialize NumUserStoriesIntegrated:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getNumUserStoriesIntegrated()));

}
if(data.size() < 7)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 6);
}

// Initialize PercentErroneous:
temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getPercentErroneous()));

}
if(data.size() < 8)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 7);
}

}
else // game over
{
data.clear();
columnNames.clear();
Vector<UserStories> userstoriess = state.getArtifactStateRepository().getUserStoriesStateRepository().getAll();
Vector<Object> temp = new Vector<Object>();
// Initialize Name:
if(columnNames.contains("Name") == false)
{
columnNames.add("Name");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
temp.add(userstoriess.elementAt(i).getName());}
if(data.size() < 1)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 0);
}

// Initialize NumUserStoriesSpecified:
if(columnNames.contains("NumUserStoriesSpecified") == false)
{
columnNames.add("NumUserStoriesSpecified");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getNumUserStoriesSpecified()));
}
if(data.size() < 2)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 1);
}

// Initialize Prioritized:
if(columnNames.contains("Prioritized") == false)
{
columnNames.add("Prioritized");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
temp.add(userstoriess.elementAt(i).getPrioritized());}
if(data.size() < 3)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 2);
}

// Initialize NumUserStoriesImplemented:
if(columnNames.contains("NumUserStoriesImplemented") == false)
{
columnNames.add("NumUserStoriesImplemented");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getNumUserStoriesImplemented()));
}
if(data.size() < 4)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 3);
}

// Initialize SpecificationCompleteness:
if(columnNames.contains("SpecificationCompleteness") == false)
{
columnNames.add("SpecificationCompleteness");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getSpecificationCompleteness()));
}
if(data.size() < 5)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 4);
}

// Initialize ImplementationCompleteness:
if(columnNames.contains("ImplementationCompleteness") == false)
{
columnNames.add("ImplementationCompleteness");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getImplementationCompleteness()));
}
if(data.size() < 6)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 5);
}

// Initialize NumUserStoriesIntegrated:
if(columnNames.contains("NumUserStoriesIntegrated") == false)
{
columnNames.add("NumUserStoriesIntegrated");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getNumUserStoriesIntegrated()));
}
if(data.size() < 7)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 6);
}

// Initialize PercentErroneous:
if(columnNames.contains("PercentErroneous") == false)
{
columnNames.add("PercentErroneous");
}temp = new Vector<Object>();
for(int i=0; i<userstoriess.size(); i++)
{
numFormat.setMinimumFractionDigits(0);
numFormat.setMaximumFractionDigits(0);
temp.add(numFormat.format(userstoriess.elementAt(i).getPercentErroneous()));
}
if(data.size() < 8)
{
data.add(temp);
}
else
{
data.setElementAt(temp, 7);
}

fireTableStructureChanged();
}

fireTableDataChanged(); // notify listeners that table data has changed
}


public Class getColumnClass(int c)
{
return getValueAt(0, c).getClass();
}
}